# Generated by Django 2.1.3 on 2018-11-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='carmodel_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sales',
            name='employee_id',
            field=models.CharField(max_length=255),
        ),
    ]
